<div class="panel panel-primary">
     <div class="panel-heading">
        <div class="panel-title">
            Resultado da Busca do Convênio ID <?php echo $this->escapeHtml($this->con_id); ?>            
        </div>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Tipo do Convenio:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_tipo"]); ?></dd>
            <dt>Numero do Convenio:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_numero"]); ?></dd>
            <dt>Valor Original:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_valor"]); ?></dd>
            <dt>Objeto:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_objeto"]); ?></dd>
             <dt>Data de Assinatura:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_data_assinatura"]); ?></dd>
            <dt>Publicação no Do:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_publicacao_do"]); ?></dd>
            <dt>Vigencia Atual:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_vigencia_atual"]); ?></dd>
           
            <dt>Data de Inicio:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_data_inicio"]); ?></dd>
            <dt>Data de Termino:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_data_termino"]); ?></dd>
            <dt>Prazo em dias:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_prazo"]); ?></dd>
            <dt>Observação:</dt>
            <dd><?php echo $this->escapeHtml($this->form["con_observacao"]); ?></dd>
            
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('form-convenio', array('action' => 'buscar', 'id' => $this->con_id)); ?>" class="btn btn-warning btn-sm">Listar Convênio</a>
        <a href="<?php echo $this->url('form-convenio'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>