<div class="topo-table">
    <a href="<?php echo $this->url('form-convenio', array('action' => 'novo')) ?>" class="btn btn-success" title="Novo"><span class="glyphicon glyphicon-plus"></span></a>

    <div class="btn-group" title="Quantidades por Página">
        <button type="button" class="btn btn-default">005</button>
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu pull-right" style="min-width: 75px" role="menu">
            <li class="active"><a href="#">005</a></li>
            <li><a href="#">010</a></li>
            <li><a href="#">025</a></li>
            <li><a href="#">050</a></li>
            <li><a href="#">100</a></li>
        </ul>
    </div>

    <form class="form-inline pull-right" role="form">
        <div class="form-group">
            <label class="sr-only" for="localizar">Buscar...</label>
            <input type="search" class="form-control" id="localizar" placeholder="Buscar">
             <a class="btn btn-xs btn-info" title="Buscar" href="<?php echo $this->url('form-convenio', array("action" => "buscar", "id" => $tb_convenio->con_id,)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                      
        </div>
        <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
    </form>
</div>

<br />

<div class="corpo-table">
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th> Tipo</th>
                <th> Numero</th>
                <th> Valor</th>
                <th> Vigencia</th>
                <th> Objeto</th>
                <th> Conveniado</th>
                <th> Data Assinatura</th>
                <th> Publicação Do </th>
                <th> Data Início</th>
                <th> Data Termino</th>
                <th> Prazo</th>
                <th> Observação </th>
                <th> Ação</th>  
            </tr>
        </thead>

        <tbody>
            <?php if(!is_array($this->formconvenio))
                     print_r("qualquer coisa");
                
                
                ?>
            <?php foreach ($this->formconvenio as $tb_convenio): ?>
                <tr>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_tipo); ?></td>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_numero); ?></td>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_valor); ?></td>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_vigencia_atual); ?></td>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_objeto); ?></td>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_data_assinatura); ?></td>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_publicacao_do); ?></td>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_data_inicio); ?></td>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_data_termino); ?></td>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_prazo); ?></td>
                    <td><?php echo $this->escapeHtml($tb_convenio->con_observacao); ?></td>


                    <td>
                        <a class="btn btn-xs btn-info" title="Visualizar" href="<?php echo $this->url('form-convenio', array("action" => "detalhes", "id" => $tb_convenio->con_id,)); ?>"><span class="glyphicon glyphicon-new-window"></span></a>
                        <a class="btn btn-xs btn-warning" title="Editar" href="<?php echo $this->url('form-convenio', array("action" => "editar", "id" => $tb_convenio->con_id,)); ?>"><span class="glyphicon glyphicon-edit"></span></a>
                        <a class="btn btn-xs btn-danger" title="Deletar" href="<?php echo $this->url('form-convenio', array("action" => "deletar", "id" => $tb_convenio->con_id,)); ?>"><span class="glyphicon glyphicon-floppy-remove"></span></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <ul class="pagination pull-right">
        <li><a href="#">Anterior</a></li>
        <li class="active"><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">Próximo</a></li>
    </ul>
</div>



<script>
<?php $this->headScript()->captureStart(); ?>

    $(function() {
        // variável para conter a url deletar
        var url_deletar = '<?php echo $this->url('form-convenio', array("action" => "deletar")); ?>' + '/';

        // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
        $("a[href*='" + url_deletar + "']").click(function(event) {
            // variável contendo o id referente ao botão clicado
            var contato_id = $(this).attr('href').split(url_deletar).pop();
            // variável contendo mensagem da janela
            var mensagem = "Deseja realmente apagar o convenio de ID " + contato_id + "?";
            // variável com resposta da mensagem colocada na janela
            var confirmacao = confirm(mensagem);

            // se a confirmação for false o fluxo é interrompido
            if (!confirmacao)
                // elimar o evendo do botão clicado
                event.preventDefault();
        });
    });

<?php $this->headScript()->captureEnd(); ?>
</script>