<div class="panel panel-primary">

    <div class="panel-heading">
        <div class="panel-title">
            Cadastro de Convênio           
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('form-convenio', array('action' => 'adicionar')); ?>">
        <div class="panel-body">
            <div class="form-group">

                <div class="form-group">
                    <label for="inputTipo" class="col-lg-3 col-md-3 control-label">Tipo Convenio</label>
                    <div class="col-lg-9  col-md-9">
                        <select class="combobox" name="con_tipo" id="tipo" itemscope="4564"  >

                            <option  value="0"> 
                                Selecione tipo de Convênio
                            </option>
                            <option  value="1"> 
                                1 - Convênio
                            </option>
                           <option  value="2"> 
                                2 - Contrato de Repasse
                            </option>
                            <option  value="3"> 
                                3 - Termo de Compromisso
                            </option>
                            <?php foreach ($this->tipoConvenio as $tb_convenio) : ?>
                                <option  value="<?= $tb_convenio->con_id ?>">  <?php echo $this->escapeHtml($tb_convenio->con_tipo); ?></option>
                            <?php endforeach; ?>
                        </select>

                    </div>
                </div>
                   <?php 
                            $element = new Zend_Form_Element_Text('con_valor');
                            $element->setLabel('Valor: R$')->setAttrib('class', 'moneyField')->addValidator(new Zend_Validate_Float(array('locale' => 'pt_BR')));
                            $this->addElement($element);  ?>
                
                <dt id="valor"><label class="optional" for="con_valor">Valor2:R$</label></dt>
                <dd id="valor-element">
                    <input type="text" class="moneyField" value="" id="valor" name="con_valor"></dd>
                
                <div class="form-group">
                    <label for="inputNumero" class="col-lg-3 col-md-3 control-label">Numero</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="con_numero" class="form-control" id="inputNumero" placeholder="Numero do Convênio" value="<?php echo $this->escapeHtml($this->form['con_numero']); ?>">     
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="inputValorOriginal" class="col-lg-3 col-md-3 control-label">Valor Original</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="con_valor" class="form-control " id="inputValorOriginal" placeholder="Valor no inicio do contrato do convenio" value="<?php echo $this->escapeHtml($this->form['con_valor']); ?>">     
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="inputVigencia" class="col-lg-3 col-md-3 control-label">Vigencia</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="con_vigencia" class="form-control data" id="inputVigencia" placeholder="Vigência" value="<?php echo $this->escapeHtml($this->form['con_vigencia4']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputObjeto" class="col-lg-3 col-md-3 control-label">Objeto</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="textarea" name="con_objeto" class="form-control" id="inputObjeto" placeholder="Descrição do Objeto" value="<?php echo $this->escapeHtml($this->form['con_objeto']); ?>">                </div>
                </div>

                <div class="form-group">
                    <label for="inputDataAssinatura" class="col-lg-3 col-md-3 control-label">Data Assinatura</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="con_data_assinatura" class="form-control data" id="inputDataAssinatura" placeholder="Data Assinatura" value="<?php echo $this->escapeHtml($this->form['con_data_assinatura']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputPublicacaoDo" class="col-lg-3 col-md-3 control-label">Publicacao DO</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="con_publicacao_do" class="form-control data" id="inputPublicacaoDo" placeholder="Publicação DO)" value="<?php echo $this->escapeHtml($this->form['con_publicacao_do']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputDataInicio" class="col-lg-3 col-md-3 control-label">Data Inicio</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="con_data_inicio" class="form-control data" id="inputDataInicio" placeholder="Data de Inicio" value="<?php echo $this->escapeHtml($this->form['con_data_inicio']); ?>">
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="inputDataTermino" class="col-lg-3 col-md-3 control-label">Data Termino</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="con_data_termino" class="form-control data" id="inputDataTermino" placeholder="Data de Termino" value="<?php echo $this->escapeHtml($this->form['con_data_termino']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputPrazo" class="col-lg-3 col-md-3 control-label">Prazo em Dias</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="con_prazo" class="form-control prazo" id="inputPrazo" placeholder="Informe Prazo em Dias" value="<?php echo $this->escapeHtml($this->form['con_prazo']); ?>">
                    </div>
                </div>  
                <div class="form-group">
                    <label for="inputObservacao" class="col-lg-3 col-md-3 control-label">Observação</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="con_observacao" class="form-control" id="inputObservacao" placeholder="Informe Observação" value="<?php echo $this->escapeHtml($this->form['grande_gerador_resp_legal']); ?>">
                    </div>
                </div>  

            </div>

            <!-- Button to trigger modal -->
            <a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>

            <!-- Modal -->
            <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 id="myModalLabel">Modal header</h3>
                </div>
                <div class="modal-body">
                    <p>One fine body…</p>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <button class="btn btn-primary">Save changes</button>
                </div>
            </div>


            <div class="modal hide fade">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3>Modal header</h3>
                </div>
                <div class="modal-body">
                    <p>One fine body…</p>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn">Close</a>
                    <a href="#" class="btn btn-primary">Save changes</a>
                </div>
            </div>


            <div class="panel-footer">
                <button type="submit" class="btn btn-primary" >Salvar Convênio</button>
                <a href="<?php echo $this->url('form-convenio'); ?>" class="btn btn-default">Voltar</a>
            </div>
    </form>
</div>

<script type="text/javascript">

<?php $this->headScript()->captureStart(); ?>

    $(document).ready(function() {
        // jQuery.noConflict();
        // alert('Teste');

        $('.fone').mask('(99) 999-9999'); //telefone
        $('cnpj').mask("99.999.999/9999-99");
        $('.cpf').mask("999.999.999-99");
        $('.cpf-sem-underline').mask("999.999.999-99", {placeholder: " "});
        $('.nascimento').mask("99/99/9999");
        $('.placa').mask("aaa-9999");
        $('.cep').mask("99999-999");
        $('.cnpj').mask("99.999.999/9999-99");
        $('.telefone').mask("(99) 9999-9999");
        $('.fax').mask("(99) 9999-9999");
        $('.inscricao-estadual').mask("999.999.999.999");
        $('.numero-contrato').mask("999.999-99/9999");
        $('.data').mask("99/99/9999");
        $('.prazo').mask("999");
        

    });

    function chamaURL(campo) {

        alert('Teste');
        document.location.href = "http://www.teste.com.br" + campo.options[campo.selectedIndex].value;
    }



    $(function() {
        // variável para conter a url deletar
        //var url_deletar = '<?php echo $this->url('form-convenio', array("action" => "deletar")); ?>' + '/';

        // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
//        $('.cpf').focusout((function(event) {
//            // variável contendo o id referente ao botão clicado
//         //   var contato_id = $(this).attr('href').split(url_deletar).pop();
//            // variável contendo mensagem da janela
//            var mensagem = "Deseja realmente apagar o contato de ID " + contato_id + "?";
//            // variável com resposta da mensagem colocada na janela
//            var confirmacao = confirm(mensagem);
//
//            // se a confirmação for false o fluxo é interrompido
//            if (!confirmacao)
//                // elimar o evendo do botão clicado
//                event.preventDefault();
//        });
    });



//        jQuery(function() {
//            jQuery("#cpf").mask("999.999.999-99");
//            jQuery("#cpf-sem-underline").mask("999.999.999-99", {placeholder: " "});
//            jQuery("#nascimento").mask("99/99/9999");
//            jQuery("#placa").mask("aaa-9999");
//            jQuery("#cep").mask("99999-999");
//            jQuery("F#cnpj").mask("99.999.999/9999-99");
//            jQuery("#telefone").mask("(99) 9999-9999");
//            jQuery("#fax").mask("(99) 9999-9999");
//            jQuery("#inscricao-estadual").mask("999.999.999.999");
//        });

<?php $this->headScript()->captureEnd(); ?>

</script>