<div class="panel panel-primary">
     <div class="panel-heading">
        <div class="panel-title">
            Detalhes Convenio ID <?php echo $this->escapeHtml($this->grande_gerador_id); ?>            
        </div>
    </div>
    <div class="panel-body">
        <dl class="dl-horizontal">
            <dt>Nome:</dt>
            <dd><?php echo $this->escapeHtml($this->form["nome"]); ?></dd>
            <dt>Telefone Principal:</dt>
            <dd><?php echo $this->escapeHtml($this->form["telefone_principal"]); ?></dd>
            <dt>Telefone Secundario:</dt>
            <dd><?php echo $this->escapeHtml($this->form["telefone_secundario"]); ?></dd>
            <dt>Data Criação:</dt>
            <dd><?php echo $this->escapeHtml($this->form["data_criacao"]); ?></dd>
            <dt>Data Atualização:</dt>
            <dd><?php echo $this->escapeHtml($this->form["data_atualizacao"]); ?></dd>
        </dl>
    </div>
    <div class="panel-footer">
        <a href="<?php echo $this->url('convenios', array('action' => 'editar', 'id' => $this->grande_gerador_id)); ?>" class="btn btn-warning btn-sm">Editar Convenio</a>
        <a href="<?php echo $this->url('convenios'); ?>" class="btn btn-default btn-sm">Voltar</a>
    </div>
</div>