<div class="panel panel-primary">

    <div class="panel-heading">
        <div class="panel-title">
            Tela Cadastro Grande Gerador           
        </div>
    </div>
    <form class="form-horizontal" role="form" method="POST" action="<?php echo $this->url('grande-gerador', array('action' => 'adicionar')); ?>">
        <div class="panel-body">
            <div class="form-group">

                <div class="form-group">
                    <label for="inputTelefonePrincipal" class="col-lg-3 col-md-3 control-label">Empresa Prestadora</label>
                    <div class="col-lg-9  col-md-9">
                        <select class="combobox" name="emp_prestadora_fk" id="emp_prestadora_fk" itemscope="4564"  >

                            <option  value="0"> 
                                Selecione uma empresa prestadora
                            </option>
                            <?php foreach ($this->empresaPrestadora as $emp_prestadora) : ?>
                                <option  value="<?= $emp_prestadora->emp_prest_id ?>">  <?php echo $this->escapeHtml($emp_prestadora->emp_prest_nome_fantasia); ?></option>
                            <?php endforeach; ?>
                        </select>

                    </div>
                </div>

                <div class="form-group">
                    <label for="inputNomeFantasia" class="col-lg-3 col-md-3 control-label">Nome Fantasia</label>
                    <div class="col-lg-9 col-md-9">
                        <input type="text" name="grande_gerador_nome_fantasia" class="form-control" id="inputNomeFantasia" placeholder="Nome Completo" value="<?php echo $this->escapeHtml($this->form['grande_gerador_nome_fantasia']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputRazaoSocial" class="col-lg-3 col-md-3 control-label">Razão Social</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_razao_social" class="form-control" id="inputRazaoSocial" placeholder="Digite seu telefone principal" />      
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputCnpj" class="col-lg-3 col-md-3 control-label">CNPJ</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_cnpj" class="form-control cnpj" id="inputTelefonePrincipal" placeholder="Digite seu telefone principal" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cnpj']); ?>">                </div>
                </div>


                <div class="form-group">
                    <label for="inputRua" class="col-lg-3 col-md-3 control-label">Rua</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_rua" class="form-control" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_rua']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputBairro" class="col-lg-3 col-md-3 control-label">Bairro</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_barro" class="form-control" id="inputTelefoneSecundario" placeholder="Digite o seu bairro(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_barro']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputCep" class="col-lg-3 col-md-3 control-label">CEP</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_cep" class="form-control cep" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_cep']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputTelefone" class="col-lg-3 col-md-3 control-label">Telefone</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_telefone" class="form-control telefone" id="inputTelefoneSecundario" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_telefone']); ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail" class="col-lg-3 col-md-3 control-label" pattern="^@\w{2,}" >Email</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_email" class="form-control" id="inputEmail" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_email']); ?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputRespLegal" class="col-lg-3 col-md-3 control-label">Responsável Legal</label>
                    <div class="col-lg-9  col-md-9">
                        <input type="text" name="grande_gerador_resp_legal" class="form-control" id="inputRespLegal" placeholder="Digite seu telefone secundário(opcional)" value="<?php echo $this->escapeHtml($this->form['grande_gerador_resp_legal']); ?>">
                    </div>
                </div>  





            </div>

            <!-- Button to trigger modal -->
            <a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>

            <!-- Modal -->
            <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h3 id="myModalLabel">Modal header</h3>
                </div>
                <div class="modal-body">
                    <p>One fine body…</p>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                    <button class="btn btn-primary">Save changes</button>
                </div>
            </div>


            <div class="modal hide fade">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3>Modal header</h3>
                </div>
                <div class="modal-body">
                    <p>One fine body…</p>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn">Close</a>
                    <a href="#" class="btn btn-primary">Save changes</a>
                </div>
            </div>









            <div class="panel-footer">
                <button type="submit" class="btn btn-primary" >Salvar Contato</button>
                <a href="<?php echo $this->url('grande-gerador'); ?>" class="btn btn-default">Voltar</a>
            </div>
    </form>
</div>

<script type="text/javascript">

<?php $this->headScript()->captureStart(); ?>

    $(document).ready(function() {
        // jQuery.noConflict();
        // alert('Teste');

        $('.fone').mask('(99) 999-9999'); //telefone
        $('cnpj').mask("99.999.999/9999-99");
        $('.cpf').mask("999.999.999-99");
        $('.cpf-sem-underline').mask("999.999.999-99", {placeholder: " "});
        $('.nascimento').mask("99/99/9999");
        $('.placa').mask("aaa-9999");
        $('.cep').mask("99999-999");
        $('.cnpj').mask("99.999.999/9999-99");
        $('.telefone').mask("(99) 9999-9999");
        $('.fax').mask("(99) 9999-9999");
        $('.inscricao-estadual').mask("999.999.999.999");

    });

    function chamaURL(campo) {

        alert('Teste');
        document.location.href = "http://www.teste.com.br" + campo.options[campo.selectedIndex].value;
    }


    $(function() {
        // variável para conter a url deletar
        //var url_deletar = '<?php echo $this->url('grande-gerador', array("action" => "deletar")); ?>' + '/';

        // qualquer link que tiver a url deletar vai sofrer um evento quando for clicada
//        $('.cpf').focusout((function(event) {
//            // variável contendo o id referente ao botão clicado
//         //   var contato_id = $(this).attr('href').split(url_deletar).pop();
//            // variável contendo mensagem da janela
//            var mensagem = "Deseja realmente apagar o contato de ID " + contato_id + "?";
//            // variável com resposta da mensagem colocada na janela
//            var confirmacao = confirm(mensagem);
//
//            // se a confirmação for false o fluxo é interrompido
//            if (!confirmacao)
//                // elimar o evendo do botão clicado
//                event.preventDefault();
//        });
    });



//        jQuery(function() {
//            jQuery("#cpf").mask("999.999.999-99");
//            jQuery("#cpf-sem-underline").mask("999.999.999-99", {placeholder: " "});
//            jQuery("#nascimento").mask("99/99/9999");
//            jQuery("#placa").mask("aaa-9999");
//            jQuery("#cep").mask("99999-999");
//            jQuery("F#cnpj").mask("99.999.999/9999-99");
//            jQuery("#telefone").mask("(99) 9999-9999");
//            jQuery("#fax").mask("(99) 9999-9999");
//            jQuery("#inscricao-estadual").mask("999.999.999.999");
//        });

<?php $this->headScript()->captureEnd(); ?>

</script>